import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Top Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main  className={styles.main}>
      <h1>Top Coder</h1>
      <img className={styles.myimg} src="/hunter.avif" alt="coder image" />
      <p className={styles.des}>A blog for Coders by a coder.</p>
      <div className={styles.blogs}>
        <div className="blogItem">
          <h2>Popular Blogs</h2>
          <br/>
          <h3>How to learn javascript in 2023.</h3>
          <p>Javascript is language of web.</p>
        </div>
      </div>
      </main>
    </>
  )
}
